### ISSUE TITLE
Load scripts from non-AppImage location

### ISSUE THREAD

**Issue by baruch** [nallath/PostProcessingPlugin#48] opened 2017-06-30 14:40 UTC
I'm interested in creating scripts for the PostProcessingPlugin but Cura is too complex to be built by a mere mortal and the plugin doesn't seem to load scripts that are just plain in the file system and is limited to only those in the AppImage.

Please add support to load user scripts from some user accessible location.

**Comment by nallath** [comment] 2017-06-30 15:32
I'll have a look if I can find an easy solution for this.

**Comment by Ghostkeeper** [comment] 2017-07-06 07:14
The problem is to actually import the thing. We currently use `pkgutil` but I think we'd need to switch to `imp` to make that work on directories not in the Pythonpath.

**Comment by fieldOfView** [comment] 2017-10-16 10:21
Is there a reason not to make the PostProcessingPlugin look in a "postprocessing" or "scripts" folder inside the configuration folder?

**Comment by nallath** [comment] 2017-10-17 08:49
Nope. None at all. That would fix the issue.

**Comment by fieldOfView** [comment] 2017-10-17 09:10
Do you have time to work on that or shall I prepare a PR?

Update; Oops, already did it.

**Comment by hexxter** [comment] 2017-10-20 18:57
Is there a way to use my own script with the appimage?

**Comment by fieldOfView** [comment] 2017-10-20 20:30
Not easily, no. Here's an attempt to get that fixed for a future version:
https://github.com/nallath/PostProcessingPlugin/pull/51

**Comment by hexxter** [comment] 2017-10-21 14:16
when goes this fix in the appimage, what do you think? there is a schedule for this?

**Comment by nallath** [comment] 2017-10-23 12:37
I expect that it will be in the 3.1 release.

**Closed as completed** 2017-11-01 14:42 UTC
